### ISSUE TITLE
Derivative not accurate when using Local Penalization method

### ISSUE THREAD

**Issue by nrontsis** [SheffieldML/GPyOpt#87] opened 2017-04-20 13:47 UTC
I have noticed that BFGS, the optimizer of the acquisition function, fails occasionally with error [`ABNORMAL_TERMINATION_IN_LNSRCH`](http://stackoverflow.com/questions/34663539/scipy-optimize-fmin-l-bfgs-b-returns-abnormal-termination-in-lnsrch). I believe that this is caused due to a problem in the calculation of the gradient of the acquisition function.

I have added a few lines in `optimization/optimizer.py` to compare the gradients provided against a numerical approximation as calculated by [Numdifftools](https://github.com/pbrod/numdifftools). You can find the modified GPyOpt version [here](https://github.com/nrontsis/GPyOpt/commit/0be207a0d8edbed774031e54412fec2f93989f3c). Using this version and running the following example, as taken from the [Tutorial Notebooks](http://nbviewer.jupyter.org/github/SheffieldML/GPyOpt/blob/master/manual/GPyOpt_parallel_optimization.ipynb), demonstrates cases where the difference in the gradients is considerable:
```python
import GPyOpt
objective_true  = GPyOpt.objective_examples.experiments2d.branin()                 # true function
objective_noisy = GPyOpt.objective_examples.experiments2d.branin(sd = 0.1)         # noisy version
bounds = objective_noisy.bounds

domain = [{'name': 'var_1', 'type': 'continuous', 'domain': bounds[0]}, ## use default bounds
          {'name': 'var_2', 'type': 'continuous', 'domain': bounds[1]}]

batch_size = 4
num_cores = 4

from numpy.random import seed
seed(123)
BO_demo_parallel = GPyOpt.methods.BayesianOptimization(f=objective_noisy.f,
                                            domain = domain,
                                            acquisition_type = 'EI',
                                            normalize_Y = True,
                                            initial_design_numdata = 10,
                                            evaluator_type = 'local_penalization',
                                            batch_size = batch_size,
                                            num_cores = num_cores,
                                            acquisition_jitter = 0)

max_iter = 10
BO_demo_parallel.run_optimization(max_iter)
```

The above script stops in the first case where there is a difference in the gradients:
```
Analytical derivative: [ -987.01491143  3251.02843774]
Numerical derivative: [ 0.  0.]
Location x: [[  1.431074    11.11493328]]
```

**Comment by javiergonzalezh** [comment] 2017-04-20 15:35
Hi,

Thanks for pointing this out. Let me have a look and I'll get back to you
asap.

Javier

**Comment by nrontsis** [comment] 2017-05-07 18:01
Any updates on this? I am planning on submitting a paper on Bayesian Optimization in two weeks and it would be really nice to compare also against your algorithm.

**Comment by javiergonzalezh** [comment] 2017-11-13 13:56
Hi @nrontsis,

Sorry for the late response on this one. Have you tried by any chance to see if you still have the issue after the new release we did a few weeks ago?

**Comment by javiergonzalezh** [comment] 2017-11-13 17:44
I think I know what the issue is. By default, in LP the EI acquisition is transformed using log, which causes stability problems when the EI is close to zero and gradients to be inaccurate. This doesn't cause major problems in the optimization itself as when the EI is flat in a region, the optimizer cannot move anyway, but it causes an abnormal termination instead because of the division by zero. I'll improve the code to cover this case.

**Comment by nrontsis** [comment] 2017-11-27 15:27
@javiergonzalezh Thank you very much for the reply. :) Indeed, I do not remember having a problem with the gradients in a non-flat region. Since you implemented the handling of `ABNORMAL_TERMINATION_IN_LNSRCH` should we close the issue?

**Comment by javiergonzalezh** [comment] 2017-11-27 21:30
Great, closing now.

**Closed by javiergonzalezh** 2017-11-27 21:30 UTC
