### ISSUE TITLE
Format of multivariate objective functions

### ISSUE THREAD

**Issue by ahyoussef** [SheffieldML/GPyOpt#72] opened 2017-02-28 19:58 UTC
What is the exact format I need to use to define a two parameter function to optimize. For instance: 

```
def func(var_1, var_2):
    return var_1**2 + var_2**2

domain = [{'name': 'var_1', 'type': 'continuous', 'domain': (-1, 1)},
          {'name': 'var_2', 'type': 'continuous', 'domain': (-1, 1)}]

BO = GPyOpt.methods.BayesianOptimization(f=func, domain = domain)
```

returns the error: 

`func() missing 1 required positional argument: 'var_2'`

Thanks.

**Comment by javiergonzalezh** [comment] 2017-03-07 22:30
Hi, the objective function should take as input and output numpy arrays. That's why you are getting the error (you have the two variables as separated arguments).

Javier

**Comment by javiergonzalezh** [comment] 2017-03-07 22:36
I'll close this one but please re-open if it is not clear.

**Closed by javiergonzalezh** 2017-03-07 22:36 UTC

**Comment by ahyoussef** [comment] 2017-03-21 12:51
Thanks for your answer. I am still unable to get this right:

```
def func(x):
    return np.array([x[0]**2+x[1]**2])

domain = [{'name': 'var_1', 'type': 'continuous', 'domain': (-1, 1)},
          {'name': 'var_2', 'type': 'continuous', 'domain': (-1, 1)}]

BO = GPyOpt.methods.BayesianOptimization(f=func, domain = domain)
```
returns the error: 

 `IndexError: index 1 is out of bounds for axis 0 with size 1`

**Comment by javiergonzalezh** [comment] 2017-03-22 09:44
Hi, the problem is in the input and output of the objective function. They need to be 2d numpy arrays (as it is used in GPy).

Hope this helps!

Javier

**Comment by manuelsh** [comment] 2017-03-26 19:27
Hi, this was not very intuitive for me. I suggest to make it easier in future versions, e.g. the function accepts n inputs, and not a 2d numpy arrays with all the inputs.
